### ISSUE TITLE
Undefined Slime Variables?

### ISSUE THREAD

**Issue by JiaHong-Lee** [Shinmera/.emacs#2]
Hi, I come here from the https://github.com/portacle/emacsd since there is no issue tracking there and I see that you have similar Lisp config to it.

I'm using slime version 20210214 from Melpa. I don't see these two variables anywhere in `C-h v`:
```lisp
(setq slime-repl-history-remove-duplicates t)
(setq slime-repl-history-trim-whitespaces t)
```
After a little of tinkering, I figure out that SLIME REPL will remove duplicates no matter the value of  `slime-repl-history-remove-duplicates`. As for trim whitespaces, I'm not sure.

**Comment by Shinmera** [comment]
Well, I guess these variables are obsolete these days. I don't keep track of upstream changes much, so it's quite possible there's a few variables in the config that are no longer needed.

**Comment by JiaHong-Lee** [comment]
I see, thank you!
